export const mockTokenAbi = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function mint(address to, uint256 amount)",
  "function approve(address spender, uint256 amount) returns (bool)",
] as const;

export const fairJackPoolAbi = [
  "function token() view returns (address)",
  "function COMMITTEE_SIZE() view returns (uint256)",
  "function MIN_VALIDATOR_COLLATERAL() view returns (uint256)",
  "function VALIDATOR_COLLATERAL_PER_GAME() view returns (uint256)",
  "function VALIDATOR_SLASH_AMOUNT() view returns (uint256)",
  "function MAX_VALIDATOR_ACTIVE_GAMES() view returns (uint256)",
  "function MIN_BET() view returns (uint256)",
  "function MAX_BET() view returns (uint256)",
  "function COMMIT_DURATION() view returns (uint256)",
  "function REVEAL_DURATION() view returns (uint256)",
  "function ACTION_DURATION() view returns (uint256)",
  "function poolBalance() view returns (uint256)",
  "function lockedLiquidity() view returns (uint256)",
  "function totalShares() view returns (uint256)",
  "function sharesOf(address user) view returns (uint256)",
  "function validators(address validator) view returns (bool registered, uint256 collateral, uint256 activeGames, uint256 slashCount)",
  "function validatorList(uint256 index) view returns (address)",
  "function nextGameId() view returns (uint256)",
  "function getValidatorCount() view returns (uint256)",
  "function getAvailableLiquidity() view returns (uint256)",
  "function getSharePrice() view returns (uint256)",
  "function depositToHousePool(uint256 amount)",
  "function withdrawFromHousePool(uint256 shares)",
  "function registerAsValidator(uint256 collateral)",
  "function unregisterAsValidator()",
  "function addValidatorCollateral(uint256 amount)",
  "function withdrawValidatorCollateral(uint256 amount)",
  "function startPoolGame(uint256 bet) returns (uint256 gameId)",
  "function submitPlayerCommit(uint256 gameId, bytes32 commitment)",
  "function submitValidatorCommit(uint256 gameId, bytes32 commitment)",
  "function revealPlayerSecret(uint256 gameId, bytes32 secret)",
  "function revealValidatorSecret(uint256 gameId, bytes32 secret)",
  "function computeCommitment(bytes32 secret, uint256 gameId, address participant) view returns (bytes32)",
  "function hit(uint256 gameId)",
  "function stand(uint256 gameId)",
  "function claimTimeout(uint256 gameId)",
  "function getGameCore(uint256 gameId) view returns (address player, uint256 bet, uint256 maxPayout, uint8 state)",
  "function getGameValidators(uint256 gameId) view returns (address[3])",
  "function getGameDeadlines(uint256 gameId) view returns (uint256 commitDeadline, uint256 revealDeadline, uint256 actionDeadline)",
  "function getGameRandomnessProgress(uint256 gameId) view returns (bytes32 playerCommit, bool playerCommitted, bool playerRevealed, uint8 commitCount, uint8 revealCount, bytes32 finalSeed)",
  "function getValidatorRandomnessStatus(uint256 gameId, address validator) view returns (bytes32 commitment, bool committed, bool revealed)",
  "function getPlayerCards(uint256 gameId) view returns (uint8[])",
  "function getDealerCards(uint256 gameId) view returns (uint8[])",
  "function getCardNonce(uint256 gameId) view returns (uint256)",
  "function isCardDrawn(uint256 gameId, uint8 card) view returns (bool)",
  "function getPlayerScore(uint256 gameId) view returns (uint256)",
  "function getDealerScore(uint256 gameId) view returns (uint256)",
  "function getGameResult(uint256 gameId) view returns (uint8 result, uint256 payout)",
  "event PoolGameStarted(uint256 indexed gameId, address indexed player, uint256 bet, uint256 maxPayout)",
  "event GameFinished(uint256 indexed gameId, uint8 result, uint256 payout, uint256 playerScore, uint256 dealerScore)",
  "event GameCancelled(uint256 indexed gameId)",
  "error ZeroAmount()",
  "error ZeroShares()",
  "error ZeroSharesMinted()",
  "error ZeroWithdrawalAmount()",
  "error InsolventPool()",
  "error InsufficientShares(uint256 available, uint256 requested)",
  "error InsufficientAvailableLiquidity(uint256 available, uint256 requested)",
  "error AlreadyRegisteredValidator()",
  "error NotRegisteredValidator()",
  "error InsufficientValidatorCollateral(uint256 minimum, uint256 provided)",
  "error ValidatorHasActiveGames(uint256 activeGames)",
  "error InsufficientWithdrawableCollateral(uint256 available, uint256 requested)",
  "error InsufficientEligibleValidators(uint256 required, uint256 available)",
  "error ValidatorCapacityReached(address validator)",
  "error BetBelowMinimum(uint256 minimum, uint256 provided)",
  "error BetAboveMaximum(uint256 maximum, uint256 provided)",
  "error InsufficientTokenAllowance(uint256 available, uint256 required)",
  "error GameDoesNotExist(uint256 gameId)",
  "error InvalidGameState(uint8 expected, uint8 actual)",
  "error GameDeadlinePassed(uint256 deadline, uint256 currentTimestamp)",
  "error GameDeadlineNotReached(uint256 deadline, uint256 currentTimestamp)",
  "error TimeoutUnavailable(uint8 state)",
  "error NotGamePlayer(address caller)",
  "error NotSelectedValidator(address caller)",
  "error InvalidCommitment()",
  "error CommitAlreadySubmitted(address participant)",
  "error SecretAlreadyRevealed(address participant)",
  "error SecretDoesNotMatchCommit(address participant)",
] as const;
